### ISSUE TITLE
0755 giving error in Settings.save_settings (line 78)

### ISSUE THREAD

**Issue by nachocho** [glvnst/usersettings#3]
Just doing a simple:
from usersettings import Settings

in Python 3.8 gives this error:

  File ".../venv/lib/python3.8/site-packages/usersettings.py", line 78
    os.makedirs(self.settings_directory, 0755)
                                            ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers

**Comment by glvnst** [comment]
Thanks for the feedback. This is fixed as part of the python3-compat PR I finally got around to merging.
