### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by djmattyg007** [glvnst/usersettings#4]
With the python3 compatibility patch having been merged, it would be great to have a new tagged & published release.

**Comment by glvnst** [comment]
good point. ok I'll get this rolled out this weekend.

**Comment by glvnst** [comment]
Release published to [pypi](https://pypi.org/project/usersettings/1.1.4/) and [github](https://github.com/glvnst/usersettings/releases/tag/1.1.4). Thanks for your help moving this along and sorry about the delay.
